### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by XL-H** [zjucz/academic-homepage#1]
Hi，请问一下你们那篇龋齿分割论文用的数据集要怎么获取呢？感谢！

**Comment by zjucz** [comment]
Hello，龋齿相关数据集的知识产权属于浙江省口腔医院，我们计划之后会公开一个完全脱敏的数据集出来，感谢关注。

**Comment by XL-H** [comment]
哦哦。好的，谢谢啦



发自我的iPad


------------------ 原始邮件 ------------------
发件人: Zheng Cao ***@***.***&gt;
发送时间: 2022年5月5日 11:13
收件人: zjucz/academic-homepage ***@***.***&gt;
抄送: XL-H ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[zjucz/academic-homepage] 数据集 (Issue #1)





 
Hello，龋齿相关数据集的知识产权属于浙江省口腔医院，我们计划之后会公开一个完全脱敏的数据集出来，感谢关注。
